server:
  port: 8000 # 服务端口
spring:
  application:
    name: gulimall-member #应用名
  #数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.136.10:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    # Nacos注册中心
    nacos:
      discovery:
        server-addr: 192.168.136.10:8848 # Nacos注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.136.10:8858
  zipkin:
    base-url: http://192.168.136.10:9411 # zipkin服务器地址端口
    discovery-client-enabled: false # 关闭服务发现，否则SpringCloud会把zipkin的url当做服务名称
    sender:
      type: web # http方式传输数据
    sleuth:
      sampler:
        probability: 1 # 设置抽样采集率100%，默认0.1=>10%
#Mybatis-Plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # mapper映射文件位置
  global-config:
    db-config:
      id-type: auto  # 主键位置
# 自定义线程池配置
gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true