server:
  port: 10000 # 服务端口
spring:
  application:
    name: gulimall-product #应用名
  #  数据源
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.136.10/gulimall_pms
  cloud:
    # Nacos注册中心
    nacos:
      discovery:
        server-addr: 192.168.136.10:8848 # Nacos注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.136.10:8858
    alicloud:
      # 阿里巴巴对象存储OSS
      access-key: LTAI5t8UkdrDyhgif4V3Ui1L
      secret-key: 1aedjRQld2T9e6Ar84jGMpra43zbb4
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 192.168.136.10
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true #是否使用前缀
      key-prefix: CACHE_ #前缀
      cache-null-values: true #是否缓存空值，可以用去解决缓存穿透问题
  session:
    store-type: redis
mybatis-plus:
  #  mapper映射文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
      #      logic-delete-field:
      logic-delete-value: 0
      logic-not-delete-value: 1
# 修改日志级别，com.zyj.gulimall包下的都会打印日志
logging:
  level:
    com.zyj.gulimall: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 1000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
# 自定义线程池配置
gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true # 开启Feign的熔断功能