server:
  port: 7000 # 服务端口
spring:
  application:
    name: gulimall-coupon #应用名
  cloud:
    # Nacos注册中心
    nacos:
      discovery:
        server-addr: 192.168.136.10:8848 # Nacos注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.136.10:8858
  #数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.136.10:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
#Mybatis-Plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # mapper映射文件位置
  global-config:
    db-config:
      id-type: auto  # 主键位置
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true