server:
  port: 9000 # 服务端口
spring:
  application:
    name: gulimall-order #应用名
  #数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.136.10:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    # Nacos注册中心
    nacos:
      discovery:
        server-addr: 192.168.136.10:8848 # Nacos注册中心地址
    # Sentinel
    sentinel:
      transport:
        dashboard: 192.168.136.10:8858
  # rabbitmq
  rabbitmq:
    host: 192.168.136.10
    virtual-host: /
    publisher-confirm-type: CORRELATED # 开启发送端确认
    publisher-returns: true # 开启发送端消息抵达队列的确认
    template:
      mandatory: true # 只要抵达队列，以异步发送优先回调我们这个returnconfirm
    listener:
      simple:
        acknowledge-mode: manual # 客户端手动确认收消息
  redis:
    host: 192.168.136.10
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    cache: false
#Mybatis-Plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # mapper映射文件位置
  global-config:
    db-config:
      id-type: auto  # 主键位置
# 自定义线程池配置
gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10
alipay:
  app_id: 2021000119617444
  notify_url: http://2bxi93.natappfree.cc/payed/notify
  return_url: http://member.gulimall.com/memberOrder.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true