spring:
  #数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.136.10:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    # Nacos注册中心
    nacos:
      server-addr: 192.168.136.10:8848 # Nacos注册中心地址
  application:
    name: gulimall-order #应用名
#Mybatis-Plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # mapper映射文件位置
  global-config:
    db-config:
      id-type: auto  # 主键位置
server:
  port: 9000 # 服务端口