server:
  port: 12000
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.10:8848
    sentinel:
      transport:
        dashboard: 192.168.136.10:8858
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://192.168.136.10:9411 # zipkin服务器地址端口
    discovery-client-enabled: false # 关闭服务发现，否则SpringCloud会把zipkin的url当做服务名称
    sender:
      type: web # http方式传输数据
    sleuth:
      sampler:
        probability: 1 # 设置抽样采集率100%，默认0.1=>10%
# elasticsearch
elasticsearch:
  hostname: 192.168.136.10
  port: 9200
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true