spring:
  application:
    name: gulimall-third-party #应用名
  cloud:
    # Nacos注册中心
    nacos:
      discovery:
        server-addr: 192.168.136.10:8848 # Nacos注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.136.10:8858
    alicloud:
      # 阿里巴巴对象存储OSS
      access-key: LTAI5t8UkdrDyhgif4V3Ui1L
      secret-key: 1aedjRQld2T9e6Ar84jGMpra43zbb4
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-zhenyj
      # 短信接口配置
      sms:
        host: https://cxkjsms.market.alicloudapi.com
        path: /chuangxinsms/dxjk
        method: POST
        appcode: a09cde2e61fe4f82988db28365c7e173
  zipkin:
    base-url: http://192.168.136.10:9411 # zipkin服务器地址端口
    discovery-client-enabled: false # 关闭服务发现，否则SpringCloud会把zipkin的url当做服务名称
    sender:
      type: web # http方式传输数据
    sleuth:
      sampler:
        probability: 1 # 设置抽样采集率100%，默认0.1=>10%
server:
  port: 30000 # 服务端口
# 修改日志级别，com.zyj.gulimall包下的都会打印日志
logging:
  level:
    com.zyj.gulimall: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true