spring:
  cloud:
    # Nacos注册中心
    nacos:
      server-addr: 192.168.136.10:8848 # Nacos注册中心地址
    alicloud:
      # 阿里巴巴对象存储OSS
      access-key: LTAI5t8UkdrDyhgif4V3Ui1L
      secret-key: 1aedjRQld2T9e6Ar84jGMpra43zbb4
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-zhenyj
      # 短信接口配置
      sms:
        host: https://cxkjsms.market.alicloudapi.com
        path: /chuangxinsms/dxjk
        method: POST
        appcode: a09cde2e61fe4f82988db28365c7e173
  application:
    name: gulimall-third-party #应用名
server:
  port: 30000 # 服务端口
# 修改日志级别，com.zyj.gulimall包下的都会打印日志
logging:
  level:
    com.zyj.gulimall: debug